// Code generated by protoc-gen-go. DO NOT EDIT.
// source: week3/week3.proto

package week3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("week3/week3.proto", fileDescriptor_d68939f9e825a960) }

var fileDescriptor_d68939f9e825a960 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4f, 0x4d, 0xcd,
	0x36, 0xd6, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x91, 0x30,
	0x97, 0xa0, 0x73, 0x62, 0x4e, 0x72, 0x69, 0x4e, 0x62, 0x49, 0x7e, 0x51, 0x70, 0x6a, 0x51, 0x59,
	0x66, 0x72, 0xaa, 0x13, 0x7b, 0x14, 0x44, 0x36, 0x89, 0x0d, 0xac, 0xd6, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xd6, 0x7d, 0x5b, 0x11, 0x40, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "week3.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "week3/week3.proto",
}
